"use client";
import { useEffect, useState, type FormEvent } from 'react';
import Link from 'next/link';
import fixture from '@/lib/integrations/fixtures/user-profile.layla.json';
type Business={id:number;name:string};
type Step={id:string;title_ar:string;status:string;locked:boolean};
type Result={message?:string;data?:unknown;error?:string};
export default function BackendDemo() {
 const [businesses,setBusinesses]=useState<Business[]>([]);const [selected,setSelected]=useState('');
 const [profile,setProfile]=useState(JSON.stringify({language:fixture.language,personal:{...fixture.personal,nationalId:'',email:'layla@example.test'},business:fixture.business},null,2));
 const [busy,setBusy]=useState(false);const [status,setStatus]=useState('');const [result,setResult]=useState<Result|null>(null);const [steps,setSteps]=useState<Step[]>([]);const [roles,setRoles]=useState<{role?:string;partner_key?:string}|null>(null);
 const [slots,setSlots]=useState<{key:string;payload:{starts_at:string}}[]>([]);const [slot,setSlot]=useState('');const [partnerKeys,setPartnerKeys]=useState('jedco_hbb');const [consent,setConsent]=useState(false);
 const [catalog,setCatalog]=useState('');const [roleUser,setRoleUser]=useState('');const [rolePartner,setRolePartner]=useState('jedco_hbb');const [role,setRole]=useState('partner');
 async function call(path:string,method='GET',body?:unknown) {const response=await fetch(path,{method,cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Request failed');return data;}
 async function run(action:()=>Promise<Result>,label:string) {setBusy(true);setStatus('جارٍ التنفيذ…');try{const value=await action();setResult(value);setStatus(`نجح: ${label}`);}catch(error){setResult(null);setStatus(error instanceof Error?error.message:'تعذر الاتصال.');}finally{setBusy(false);}}
 async function load() {const value=await call('/api/business');setBusinesses(value.data);if(value.data.length)setSelected(String(value.data[0].id));const me=await call('/api/platform/me');setRoles(me.membership);}
 useEffect(()=>{
  async function initialize(){const response=await fetch('/api/business',{cache:'no-store'});const value=await response.json();if(!response.ok)throw new Error(value.error);setBusinesses(value.data);if(value.data.length)setSelected(String(value.data[0].id));const meResponse=await fetch('/api/platform/me',{cache:'no-store'});const me=await meResponse.json();if(!meResponse.ok)throw new Error(me.error);setRoles(me.membership);}
  void initialize().catch(error=>setStatus(error.message));
 },[]);
 const root=`/api/platform/businesses/${selected}`;
 async function roadmap() {const value=await call(root+'/roadmap');setSteps(value.data.steps);return value;}
 function profileValue(){return JSON.parse(profile);}
 async function upload(event:FormEvent<HTMLFormElement>) {
  event.preventDefault();const form=event.currentTarget;const file=new FormData(form).get('file') as File;if(!file?.size)return;
  await run(async()=>{const value=await call(root+'/documents/upload','POST',{filename:file.name,mimeType:file.type,sizeBytes:file.size,kind:'other'});const sent=await fetch(value.upload.signedUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!sent.ok)throw new Error('File upload failed');return call(`/api/platform/documents/${value.data.id}/finalize`,'POST',{});},'رفع الملف والتحقق منه');form.reset();
 }
 const button='rounded-md bg-teal-700 px-3 py-2 text-white disabled:opacity-40';
 const control='w-full rounded-md border p-2 bg-white text-slate-900';
 return <main dir="rtl" className="min-h-screen bg-slate-50 text-slate-900 p-6"><div className="mx-auto max-w-4xl space-y-6">
  <header><Link href="/" className="text-teal-700">← حسابي</Link><h1 className="text-2xl font-bold">لوحة تجربة وتسليم Member 4</h1><p>بيانات القواعد من الفريق. الطلبات داخل النظام فقط؛ البنك والمواعيد والتقويم والموقع بيانات تجريبية.</p></header>
  <p role="status" className="rounded border bg-white p-3">{status||'اختر مشروعًا لبدء التجربة.'}</p>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">المشروع</h2><select aria-label="المشروع" value={selected} onChange={event=>{setSelected(event.target.value);setSteps([]);}} className={control}><option value="">اختر مشروعًا</option>{businesses.map(b=><option key={b.id} value={b.id}>{b.name} ({b.id})</option>)}</select><button disabled={busy} className={button} onClick={()=>run(async()=>{const value=await call('/api/business','POST',{name:'M4 Demo Project',type:'Home-based demo',city:'Amman'});await load();setSelected(String(value.data.id));return value;},'إنشاء مشروع تجريبي مستقل')}>إنشاء مشروع تجريبي مستقل</button></section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">1. الاستبيان وحفظ واستئناف الإجابات</h2><p>المثال التالي لشخصية ليلى التجريبية، ولا يثبت هوية SANAD. عدّل القيم ثم احفظ أو أرسل الاستبيان.</p><textarea aria-label="إجابات الاستبيان JSON" dir="ltr" rows={13} value={profile} onChange={e=>setProfile(e.target.value)} className={control}/><div className="flex flex-wrap gap-2"><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/onboarding/draft','POST',profileValue()),'حفظ المسودة')}>حفظ المسودة</button><button disabled={busy||!selected} className={button} onClick={()=>run(async()=>{const value=await call(root+'/onboarding');if(value.data?.answers){const {userId:ignored,...answers}=value.data.answers;void ignored;setProfile(JSON.stringify(answers,null,2));}return value;},'استئناف الاستبيان')}>استئناف</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/onboarding/submit','POST',profileValue()),'توليد خارطة الطريق')}>إرسال وتوليد الخارطة</button></div></section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">2. الخارطة والتقدم والتكاليف والمسار المنزلي</h2><div className="flex flex-wrap gap-2"><button disabled={busy||!selected} className={button} onClick={()=>run(roadmap,'عرض الخارطة')}>عرض الخارطة</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/estimate'),'تقدير الرسوم والوقت')}>الرسوم والوقت</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/home-track'),'المسار المنزلي')}>المسار المنزلي</button></div>{steps.map(step=><div key={step.id} className="flex justify-between items-center gap-3 border-t pt-2"><span>{step.title_ar} — {step.status}{step.locked?' 🔒':''}</span><button disabled={busy||step.locked||step.status==='done'} className={button} onClick={()=>run(async()=>{await call('/api/platform/tasks/'+step.id,'PATCH',{status:'done'});return roadmap();},'إكمال الخطوة')}>إكمال</button></div>)}</section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">3. المستندات والنموذج وخطة العمل وملف البنك</h2><form onSubmit={upload} className="flex flex-wrap gap-2"><input aria-label="رفع مستند" name="file" type="file" accept="application/pdf,image/jpeg,image/png" required/><button disabled={busy||!selected} className={button}>رفع مستند خاص</button></form><div className="flex flex-wrap gap-2"><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/documents'),'المستندات الخاصة')}>عرض المستندات</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/documents/autofill','POST',{}),'تعبئة نموذج مراجعة PDF')}>إنشاء نموذج PDF</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/plan'),'خطة العمل')}>معاينة خطة العمل</button>{selected&&<><a className={button} href={root+'/plan/pdf?lang=ar'}>تحميل الخطة PDF</a><a className={button} href={root+'/bank-package'}>تحميل ملف البنك ZIP</a></>}</div></section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">4. مطابقة الحاضنات وتسجيل الطلبات</h2><input aria-label="معرفات الشركاء" dir="ltr" value={partnerKeys} onChange={e=>setPartnerKeys(e.target.value)} className={control}/><label className="block"><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> أوافق على مشاركة الملف والمستندات المختارة مع حساب الشريك داخل عرض Bedaya التجريبي.</label><div className="flex flex-wrap gap-2"><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/incubators'),'الحاضنات المناسبة')}>عرض المطابقات</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/incubators/prefill','POST',{incubatorIds:partnerKeys.split(',').map(s=>s.trim())}),'معاينة الطلبات غير الرسمية')}>معاينة النماذج</button><button disabled={busy||!selected||!consent} className={button} onClick={()=>run(()=>call(root+'/applications','POST',{partnerKeys:partnerKeys.split(',').map(s=>s.trim()),consent:true}),'تسجيل الطلب داخل النظام فقط')}>تسجيل الطلب التجريبي</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/applications'),'حالة الطلبات')}>حالة الطلبات</button></div></section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">5. المواعيد والتقويم والنماذج الأخرى</h2><div className="flex flex-wrap gap-2"><button disabled={busy} className={button} onClick={()=>run(async()=>{const value=await call('/api/platform/slots');setSlots(value.data);setSlot(value.data[0]?.key||'');return value;},'المواعيد التجريبية')}>عرض المواعيد</button><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/compliance'),'تقويم تجريبي')}>التقويم</button><button disabled={busy} className={button} onClick={()=>run(()=>call('/api/platform/location','POST',{area:'Demo Amman Area A',activity:'retail'}),'فحص موقع تجريبي')}>الموقع التجريبي</button><button disabled={busy} className={button} onClick={()=>run(()=>call('/api/platform/analytics'),'تحليلات تجريبية مجهولة')}>التحليلات</button><button disabled={busy} className={button} onClick={()=>run(()=>call('/api/platform/identity/mock','POST',{consent:true}),'محول SANAD التجريبي')}>محول هوية تجريبي</button></div>{slots.length>0&&<div className="flex gap-2"><select aria-label="موعد تجريبي" value={slot} onChange={e=>setSlot(e.target.value)} className={control}>{slots.map(s=><option key={s.key} value={s.key}>{s.key} — {new Date(s.payload.starts_at).toLocaleString('ar-JO',{timeZone:'Asia/Amman'})}</option>)}</select><button disabled={busy||!selected} className={button} onClick={()=>run(()=>call(root+'/bookings','POST',{slotKey:slot}),'حجز تجريبي')}>حجز تجريبي</button></div>}</section>
  <section className="rounded-xl border bg-white p-4 space-y-3"><h2 className="font-bold">6. لوحة الشريك والإدارة</h2><p>الدور الحالي: {roles?.role||'صاحب مشروع'}. صلاحيات الإدارة والشريك تُمنح لحسابات محددة فقط.</p><button disabled={busy} className={button} onClick={()=>run(()=>call('/api/platform/partner/inbox'),'صندوق الشريك')}>صندوق الشريك</button><button disabled={busy} className={button} onClick={()=>run(async()=>{const value=await call('/api/platform/admin/catalog');setCatalog(JSON.stringify(value.data[0],null,2));return {message:'اختر وعدّل سجلًا من الكتالوج؛ بيانات القواعد تتطلب المحافظة على مراجع المصادر.',data:value.data.map((row:{key:string})=>row.key)};},'كتالوج الإدارة')}>كتالوج الإدارة</button>{roles?.role==='admin'&&<><textarea aria-label="سجل الكتالوج" dir="ltr" rows={10} value={catalog} onChange={e=>setCatalog(e.target.value)} className={control}/><button disabled={busy} className={button} onClick={()=>run(()=>{const {key,kind,payload,is_demo}=JSON.parse(catalog);return call('/api/platform/admin/catalog','POST',{key,kind,payload,isDemo:is_demo});},'حفظ الكتالوج')}>حفظ الكتالوج</button><input aria-label="معرف مستخدم لإدارة دوره" placeholder="User UUID" value={roleUser} onChange={e=>setRoleUser(e.target.value)} className={control}/><select aria-label="الدور" value={role} onChange={e=>setRole(e.target.value)} className={control}><option value="partner">partner</option><option value="admin">admin</option></select><input aria-label="شريك المستخدم" value={rolePartner} onChange={e=>setRolePartner(e.target.value)} className={control}/><button disabled={busy} className={button} onClick={()=>run(()=>call('/api/platform/admin/users','POST',{userId:roleUser,role,partnerKey:role==='partner'?rolePartner:null}),'حفظ دور التطبيق')}>حفظ دور التطبيق</button></>}</section>
  {result&&<details className="rounded-xl border bg-white p-4"><summary>تفاصيل استجابة API للمراجعة</summary><pre dir="ltr" className="overflow-auto text-xs whitespace-pre-wrap">{JSON.stringify(result,(key,value)=>/token|signedUrl|signedURL/i.test(key)?'[redacted]':value,2)}</pre></details>}
 </div></main>;
}
