const D=window.BEDAYA;let lang=localStorage.getItem('bedaya.lang')||'en';let state=JSON.parse(localStorage.getItem('bedaya.state')||'{}');let selected=new Set([0,1]);const $=s=>document.querySelector(s);const t=v=>Array.isArray(v)?v[lang==='ar'?1:0]:v;const c=k=>t(D.copy[k]);const escapeHtml=s=>String(s??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));const e=escapeHtml;const persist=()=>localStorage.setItem('bedaya.state',JSON.stringify(state));const icons=['◈','▤','✓','◇','▣','?','○','▦','≡','▦','⌖','◇','◎','▤'];
function go(id){location.hash=id}function toast(msg){$('#toast').textContent=msg;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',2500)}
function current(){return D.screens.find(s=>s.id===location.hash.slice(1))||D.screens[0]}function roleOf(s){return ['partner','application'].includes(s.id)?'partner':['admin','analytics'].includes(s.id)?'admin':'owner'}
function rows(s){const tags={Name:'الاسم','National ID':'الرقم الوطني',City:'المدينة',Today:'اليوم',Tomorrow:'غداً',Review:'مراجعة',HOME:'منزل',ID:'هوية',ADDR:'عنوان',PROFILE:'الملف',DOCS:'مستندات',PLAN:'خطة',RULE:'قاعدة',FEE:'رسوم',PARTNER:'شريك',USER:'مستخدم',GRANT:'منحة',LOAN:'قرض',SUPPORT:'دعم'};return `<div class="list">${(s.rows||[]).map((r,i)=>`<div class="item"><span class="lead">${e(lang==='ar'?(tags[r[0]]||r[0]):r[0])}</span><div class="details"><strong>${e(r[lang==='ar'?2:1])}</strong>${r[3]&&s.kind!=='roadmap'?`<small>${e(r[lang==='ar'?4:3])}</small>`:''}${s.kind==='analytics'?`<div class="bar"><span style="width:${Number(r[0])/5*100}%"></span></div>`:''}</div>${s.kind==='matches'?`<input type="checkbox" aria-label="${e(r[lang==='ar'?2:1])}" data-select="${i}" ${selected.has(i)?'checked':''}>`:''}${s.kind==='experts'?`<button data-book="${i}">${lang==='ar'?'حجز':'Book'}</button>`:''}${s.kind==='roadmap'?`<span class="status ${i===1?'warning':''}">${e(r[lang==='ar'?4:3])}</span>${i>1?`<button data-locked="1" aria-label="${e(c('locked'))}" title="${e(c('locked'))}">×</button>`:''}`:''}</div>`).join('')}</div>`}
function action(s){if(!s.action)return '';return `<div class="toolbar"><button class="primary" id="primary">${e(t(s.action))}</button>${s.id==='documents'?`<button id="sample">${e(c('sample'))}</button><label class="field">${e(c('upload'))}<input type="file" id="upload" accept=".pdf,.png,.jpg,.jpeg"></label>`:''}</div>`}
function calendar(){return `<div class="calendar" aria-label="October 2026">${Array.from({length:31},(_,i)=>`<div class="day ${[12,13,15].includes(i+1)?'event':''}">${i+1}</div>`).join('')}</div>`}
function body(s){if(s.kind==='wizard'){let val=state[s.field];return `<div class="wizard"><div class="eyebrow">${lang==='ar'?`الخطوة ${s.step} من ٨`:`STEP ${s.step} OF 8`}</div><div class="progress"><span style="width:${s.step/8*100}%"></span></div><h1>${e(t(s.title))}</h1><p class="subtitle">${e(t(s.sub))}</p>${s.options?`<div class="options">${s.options.map((v,i)=>`<label class="option"><input name="answer" type="radio" value="${i}" ${String(val)===String(i)?'checked':''}><span>${e(t(v))}</span></label>`).join('')}</div>`:`<label class="field"><span>${e(t(s.title))}</span><input id="answer" type="${s.input}" value="${e(val??t(s.value))}" ${s.input==='number'?'min="1" max="100000000"':''}></label>`}${s.field==='partners'?`<label class="field" id="partner-count" hidden><span>${lang==='ar'?'عدد الشركاء':'Number of partners'}</span><input id="partners-count" type="number" min="1" max="50" value="1"></label>`:''}<p id="validation" class="error" role="alert"></p><div class="toolbar"><button id="back">${c('back')}</button><button id="wizard-next" class="primary">${c('next')}</button></div></div>`}let content=rows(s);
if(s.kind==='consent')content+=`<p class="note">${e(t(s.note))}</p><label class="option"><input type="checkbox" id="consent">${e(c('consent'))}</label>`;
if(s.kind==='roadmap')content=`<div class="metrics"><div class="metric"><b>17%</b><small>${lang==='ar'?'اكتمال المسار':'Roadmap complete'}</small></div><div class="metric"><b>120 JOD</b><small>${lang==='ar'?'تقدير توضيحي':'Illustrative estimate'}</small></div><div class="metric"><b>7–14</b><small>${lang==='ar'?'أيام نموذجية':'Sample days'}</small></div></div><div class="progress"><span style="width:17%"></span></div>${content}`;
if(s.kind==='ocr')content=`<div class="split"><div class="preview"><h2>${lang==='ar'?'معاينة المستند النموذجي':'Sample document preview'}</h2><div class="lines"></div><div class="lines"></div><div class="lines"></div><div class="lines"></div><small>${c('mock')}</small></div><div>${s.rows.map((r,i)=>`<label class="field"><span>${e(t([r[0],['الاسم الكامل','اسم المشروع','المدينة'][i]]))}</span><input data-ocr="${i}" value="${e(state.ocr?.[i]||r[lang==='ar'?2:1])}"></label>`).join('')}</div></div>`;
if(s.kind==='review')content=`<div class="list">${['activity','city','premises','name','partners','capital','staff','support'].map(f=>{let q=D.screens.find(x=>x.field===f),v=state[f];return `<div class="item"><div class="details"><small>${e(t(q.title))}</small><strong>${e(q.options?t(q.options[Number(v)||0]):v||t(q.value))}</strong></div><button data-go="${q.id}">${c('review')}</button></div>`}).join('')}</div>`;
if(s.kind==='documents')content+=`<div id="upload-status" class="summary">${state.document?e(state.document):lang==='ar'?'مطلوب: نسخة أوضح من إثبات العنوان':'Required: a clearer copy of address evidence'}</div>`;
if(s.kind==='chat')content=`<div id="messages">${s.rows.map((r,i)=>`<div class="bubble ${i?'assistant':''}"><small>${e(r[0]==='You'?(lang==='ar'?'أنت':'You'):'Bedaya')}</small><p>${e(r[lang==='ar'?2:1])}</p></div>`).join('')}</div><form class="chat-form"><input id="question" required aria-label="${e(t(s.title))}" placeholder="${lang==='ar'?'اكتب سؤالك':'Type your question'}"><button class="primary">${lang==='ar'?'إرسال':'Send'}</button></form>`;
if(s.kind==='calendar')content=`${calendar()}<label class="field"><span>${c('partner')}</span><select id="appointment-partner">${s.options.map(v=>`<option>${e(t(v))}</option>`).join('')}</select></label><label class="field"><span>${lang==='ar'?'الموعد المتاح':'Available slot'}</span><select id="slot"><option>12 Oct · 09:00</option><option>12 Oct · 11:30</option><option>13 Oct · 10:00</option></select></label><div id="reservation">${state.booking?`<div class="summary">${e(state.booking)} <button id="cancel-booking">${c('cancel')}</button></div>`:''}</div>`;
if(s.kind==='compliance')content=calendar()+content;
if(s.kind==='location')content=`<label class="field"><span>${lang==='ar'?'العنوان':'Address'}</span><input id="address" value="${lang==='ar'?'إربد، عنوان تجريبي':'Irbid, sample address'}"></label><div class="map" aria-label="Illustrative map"><span class="pin">${lang==='ar'?'الموقع النموذجي':'Sample location'}</span></div><div id="location-result" hidden>${content}</div>`;
if(s.kind==='funding')content=`<label class="field"><span>${lang==='ar'?'نوع العرض':'Offer type'}</span><select id="funding-filter"><option value="all">${lang==='ar'?'الكل':'All'}</option><option value="GRANT">${lang==='ar'?'منح':'Grants'}</option><option value="LOAN">${lang==='ar'?'قروض':'Loans'}</option></select></label><div id="funding-results">${content}</div>`;
if(s.kind==='bank')content+=`<div class="options">${s.options.map((v,i)=>`<label class="option"><input type="checkbox" name="bank" ${i===0?'checked':''}>${e(t(v))}</label>`).join('')}</div>`;
if(s.kind==='partner')content=`<label class="field"><span>${c('search')}</span><input id="partner-search" placeholder="BD-1042"></label><div id="partner-results">${content}</div>`;
if(s.kind==='application')content+=`<div class="toolbar"><button id="approve" class="primary">${lang==='ar'?'الموافقة':'Approve'}</button><button id="request">${lang==='ar'?'طلب مستند':'Request document'}</button><button id="reject">${lang==='ar'?'رفض':'Reject'}</button></div><div id="decision" class="summary" hidden></div>`;
if(s.kind==='admin')content=`<div class="toolbar">${[['Rules','القواعد'],['Fees','الرسوم'],['Partners','الشركاء'],['Users','المستخدمون']].map((v,i)=>`<button data-admin-tab="${i}">${t(v)}</button>`).join('')}</div><div id="admin-content">${content}</div><label class="field"><span>${lang==='ar'?'قيمة نموذجية قابلة للتعديل':'Editable sample value'}</span><input id="admin-value" value="50"></label><button data-go="analytics">${lang==='ar'?'عرض التحليلات':'View analytics'}</button>`;
if(s.kind==='signing')content+=`<label class="option"><input type="checkbox" id="sign-consent">${lang==='ar'?'راجعت المستندات وأوافق على التوقيع التجريبي.':'I reviewed the documents and agree to a demo signature.'}</label>`;
if(s.kind==='success')content=`<div class="success-mark" aria-hidden="true">✓</div>${content}`;
return `<div class="eyebrow">${roleOf(s)==='owner'?c('home'):c(roleOf(s))}</div><h1>${e(t(s.title))}</h1><p class="subtitle">${e(t(s.sub))}</p>${s.kind==='entry'?`<div class="actions">${action(s)}</div>${content}`:content+action(s)}${s.note&&s.kind!=='consent'?`<p class="note">${e(t(s.note))}</p>`:''}`}
function render(){let s=current(),entry=['entry','consent'].includes(s.id);document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=`${t(s.title)} | Bedaya`;$('#app').innerHTML=`<header><div class="brand"><img src="logo.png" alt="بداية"><strong>Bedaya</strong><small>${c('demo')}</small></div><div class="head-actions"><button class="mobile-menu" id="menu" aria-label="Menu">☰</button><select class="role" id="role" aria-label="${c('owner')}">${['owner','partner','admin'].map(v=>`<option value="${v}" ${roleOf(s)===v?'selected':''}>${c(v)}</option>`).join('')}</select><button id="language">${c('language')}</button></div></header><div class="${entry?'entry':'shell'}">${entry?'':`<aside><div class="profile"><b>${c('profile')}</b><span>${c('verified')}</span></div><nav>${(roleOf(s)==='owner'?D.nav:roleOf(s)==='partner'?[['partner','Applications','الطلبات']]:[['admin','Management','الإدارة'],['analytics','Analytics','التحليلات']]).map((v,i)=>`<a href="#${v[0]}" class="${s.id===v[0]?'active':''}"><span class="nav-icon" aria-hidden="true">${icons[i]}</span>${e(v[lang==='ar'?2:1])}</a>`).join('')}</nav><button id="reset" style="margin-top:24px;width:100%">${c('reset')}</button></aside>`}<main>${body(s)}<footer>${c('demo')} · ${c('mock')}</footer></main></div>`;
$('#language').onclick=()=>{lang=lang==='en'?'ar':'en';localStorage.setItem('bedaya.lang',lang);render()};$('#role').onchange=x=>go({owner:'roadmap',partner:'partner',admin:'admin'}[x.target.value]);if($('#menu'))$('#menu').onclick=()=>{let a=$('aside');if(a)a.classList.toggle('open')};if($('#reset'))$('#reset').onclick=()=>{state={};persist();go('entry')};document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>go(b.dataset.go));document.querySelectorAll('[data-locked]').forEach(b=>b.onclick=()=>toast(c('locked')));document.querySelectorAll('[data-select]').forEach(b=>b.onchange=()=>b.checked?selected.add(+b.dataset.select):selected.delete(+b.dataset.select));if($('#back'))$('#back').onclick=()=>go(s.step===1?'consent':`w${s.step-1}`);
if($('#wizard-next'))$('#wizard-next').onclick=()=>{let v=s.options?$('input[name=answer]:checked')?.value:$('#answer').value;if(v===undefined||!String(v).trim()||(s.input==='number'&&(+v<1||+v>100000000))){$('#validation').textContent=c('error');return}state[s.field]=v;if(s.field==='partners'&&v==='1')state.partnerCount=$('#partners-count').value;persist();go(s.target)};
if(s.field==='partners')document.querySelectorAll('[name=answer]').forEach(b=>b.onchange=()=>$('#partner-count').hidden=b.value!=='1');
if($('#primary'))$('#primary').onclick=()=>primary(s);if($('#consent')){ $('#primary').disabled=!$('#consent').checked;$('#consent').onchange=()=>$('#primary').disabled=!$('#consent').checked}if($('#sign-consent')){$('#primary').disabled=true;$('#sign-consent').onchange=()=>$('#primary').disabled=!$('#sign-consent').checked}
if($('#sample'))$('#sample').onclick=()=>{state.document=lang==='ar'?'إثبات العنوان · نسخة نموذجية واضحة':'Address evidence · clear sample';persist();render();toast(c('success'))};if($('#upload'))$('#upload').onchange=x=>{let f=x.target.files[0];if(!f)return;if(f.size>10*1024*1024){toast(lang==='ar'?'الحد الأقصى ١٠ ميجابايت':'Maximum file size is 10 MB');return}state.document=f.name;persist();render();toast(c('success'))};
if($('.chat-form'))$('.chat-form').onsubmit=x=>{x.preventDefault();let q=$('#question').value;$('#messages').insertAdjacentHTML('beforeend',`<div class="bubble">${e(q)}</div><div class="bubble assistant">${e(t(D.screens.find(v=>v.id==='assistant').rows[1].slice(1)))}</div>`);$('#question').value=''};
if($('#cancel-booking'))$('#cancel-booking').onclick=()=>{delete state.booking;persist();render();toast(c('cancel'))};if($('#funding-filter'))$('#funding-filter').onchange=x=>$('#funding-results').innerHTML=rows({...s,rows:s.rows.filter(r=>x.target.value==='all'||r[0]===x.target.value)});if($('#partner-search'))$('#partner-search').oninput=x=>{let filtered=s.rows.filter(r=>r.join(' ').toLowerCase().includes(x.target.value.toLowerCase()));$('#partner-results').innerHTML=filtered.length?rows({...s,rows:filtered}):`<p class="summary">${c('empty')}</p>`};document.querySelectorAll('[data-admin-tab]').forEach(b=>b.onclick=()=>$('#admin-content').innerHTML=rows({...s,rows:[s.rows[+b.dataset.adminTab]]}));document.querySelectorAll('[data-book]').forEach(b=>b.onclick=()=>{state.booking=t(s.rows[+b.dataset.book].slice(1,3));persist();go('appointments')});['approve','reject','request'].forEach(k=>{if($('#'+k))$('#'+k).onclick=()=>dialog(k==='request'?(lang==='ar'?'طلب إثبات عنوان أوضح':'Request clearer address evidence'):$('#'+k).textContent,()=>{$('#decision').hidden=false;$('#decision').textContent=lang==='ar'?'تم حفظ قرار الشريك في العرض التجريبي':'Partner decision saved in demo';toast(c('success'))})});}
function dialog(title,onConfirm){let m=$('#modal');m.innerHTML=`<h2>${e(title)}</h2><p>${c('demo')}</p><label class="field"><span>${lang==='ar'?'ملاحظة':'Note'}</span><textarea id="decision-note" rows="3"></textarea></label><div class="toolbar"><button id="modal-cancel">${c('cancel')}</button><button id="modal-confirm" class="primary">${c('confirm')}</button></div>`;m.showModal();$('#modal-cancel').onclick=()=>m.close();$('#modal-confirm').onclick=()=>{m.close();onConfirm()}}
function primary(s){if(s.id==='incubators'&&!selected.size){toast(lang==='ar'?'اختر جهة واحدة على الأقل':'Select at least one partner');return}if(s.id==='bank'&&!$('input[name=bank]:checked')){toast(c('error'));return}if(['incubators','bank'].includes(s.id)){dialog(t(s.action),()=>go(s.target));return}if(s.id==='plan'){let text=t(s.title)+'\n\n'+s.rows.map(r=>r[lang==='ar'?2:1]+'\n'+r[lang==='ar'?4:3]).join('\n\n');let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));a.download='bedaya-business-plan.txt';a.click();URL.revokeObjectURL(a.href);return}if(s.id==='appointments'){state.booking=$('#appointment-partner').value+' · '+$('#slot').value;persist();render();toast(c('booked'));return}if(s.id==='notifications'){state.read=true;persist();toast(c('success'));return}if(s.id==='location'){if(!$('#address').value.trim()){toast(c('error'));return}$('#location-result').hidden=false;return}if(s.id==='admin'){state.adminValue=$('#admin-value').value;persist();toast(c('success'));return}if(s.target){if(s.id==='ocr'){state.ocr=Array.from(document.querySelectorAll('[data-ocr]')).map(x=>x.value);persist()}go(s.target)}else toast(c('success'))}
window.addEventListener('hashchange',()=>{render();window.scrollTo(0,0)});render();
