window.BEDAYA = {
  nav: [
    ['roadmap','Your roadmap','مسار مشروعك'],['documents','Documents','المستندات'],['signing','Signatures','التواقيع'],['incubators','Incubators','الحاضنات'],['bank','Bank file','الملف البنكي'],['assistant','Assistant','المساعد'],['notifications','Notifications','الإشعارات'],['appointments','Appointments','المواعيد'],['plan','Business plan','خطة العمل'],['compliance','Compliance','الالتزامات'],['location','Location','الموقع'],['funding','Funding','التمويل'],['experts','Experts','الخبراء'],['invoicing','E-invoicing','الفوترة الإلكترونية']
  ],
  copy: {
    demo:['Interactive demo · sample data','عرض تجريبي · بيانات نموذجية'],owner:['Business owner','صاحب المشروع'],partner:['Partner','الشريك'],admin:['Admin','الإدارة'],back:['Back','رجوع'],next:['Continue','متابعة'],save:['Save changes','حفظ التغييرات'],cancel:['Cancel','إلغاء'],review:['Review','مراجعة'],download:['Download','تنزيل'],empty:['Nothing here yet','لا توجد عناصر بعد'],error:['Please complete the required field.','يرجى إكمال الحقل المطلوب.'],success:['Changes saved','تم حفظ التغييرات'],search:['Search','بحث'],home:['Layla’s home bakery','مخبز ليلى المنزلي'],profile:['Layla Ahmad · Irbid','ليلى أحمد · إربد'],typed:['Entered by you','أدخلته بنفسك'],verified:['Demo identity verified','تم التحقق من الهوية التجريبية'],mock:['SANAD demo connection','اتصال سند التجريبي'],pending:['Not started','لم يبدأ'],done:['Completed','مكتمل'],needs:['Needs action','يتطلب إجراء'],submitted:['Submitted','تم الإرسال'],locked:['Complete the previous step first','أكمل الخطوة السابقة أولاً'],notice:['Illustrative details. Confirm requirements with the relevant authority.','تفاصيل توضيحية. تحقق من المتطلبات لدى الجهة المختصة.'],upload:['Upload document','رفع مستند'],sample:['Use sample document','استخدام مستند نموذجي'],signed:['Signed in demo','تم التوقيع تجريبياً'],sent:['Demo application submitted','تم إرسال الطلب التجريبي'],booked:['Appointment reserved in demo','تم حجز الموعد تجريبياً'],read:['Mark all as read','تحديد الكل كمقروء'],apply:['Apply to selected','التقديم للجهات المحددة'],sign:['Review and sign','المراجعة والتوقيع'],confirm:['Confirm','تأكيد'],reset:['Reset demo','إعادة العرض'],language:['العربية','English'],close:['Close','إغلاق'],consent:['I agree to use sample identity data in this demo.','أوافق على استخدام بيانات هوية نموذجية في هذا العرض.'],loading:['Preparing your workspace…','جارٍ إعداد مساحة العمل…']
  },
  screens: [
    {id:'entry',feature:7,title:['Your business begins here.','مشروعك يبدأ من هنا.'],sub:['Bedaya connects your next step, documents, and opportunities in one workspace.','بداية تجمع خطواتك ومستنداتك وفرصك في مساحة واحدة.'],kind:'entry',action:['Login with SANAD','تسجيل الدخول عبر سند'],target:'consent',rows:[['01','Answer once','أجب مرة واحدة','A profile that follows your whole journey.','ملف يرافقك طوال رحلتك.'],['02','Know your next step','اعرف خطوتك التالية','A clear roadmap for your business.','مسار واضح لمشروعك.'],['03','Move forward together','تقدم مع شركائك','Connect with incubators and banks.','تواصل مع الحاضنات والبنوك.']]},
    {id:'consent',feature:7,title:['Connect your identity','ربط هويتك'],sub:['Review what Bedaya will receive before continuing.','راجع البيانات التي ستستقبلها بداية قبل المتابعة.'],kind:'consent',action:['Agree and continue','الموافقة والمتابعة'],target:'w1',rows:[['Name','Layla Ahmad','ليلى أحمد'],['National ID','••••••4821','••••••4821'],['City','Irbid','إربد']],note:['This hackathon uses fictional identity data. No real SANAD connection is active.','يستخدم هذا العرض بيانات هوية افتراضية. لا يوجد اتصال فعلي بسند.']},
    {id:'w1',feature:1,title:['What would you like to start?','ما المشروع الذي تريد بدءه؟'],sub:['Choose the activity closest to your idea.','اختر النشاط الأقرب لفكرتك.'],kind:'wizard',step:1,field:'activity',options:[['Home bakery','مخبز منزلي'],['Retail shop','متجر تجزئة'],['Online store','متجر إلكتروني'],['Service company','شركة خدمات']],target:'w2'},
    {id:'w2',feature:1,title:['Where will your business be?','أين سيكون مشروعك؟'],sub:['Your city helps shape your launch steps.','تساعد مدينتك في تحديد خطوات الإطلاق.'],kind:'wizard',step:2,field:'city',options:[['Irbid','إربد'],['Amman','عمّان'],['Zarqa','الزرقاء'],['Aqaba','العقبة']],target:'w3'},
    {id:'w3',feature:13,title:['Where will you work?','من أين ستعمل؟'],sub:['Home businesses have a dedicated roadmap.','للمشاريع المنزلية مسار مخصص.'],kind:'wizard',step:3,field:'premises',options:[['From home','من المنزل'],['Rented shop','محل مستأجر'],['Owned office','مكتب مملوك']],target:'w4'},
    {id:'w4',feature:1,title:['What is your business name?','ما اسم مشروعك؟'],sub:['You can change this before submission.','يمكنك تغييره قبل الإرسال.'],kind:'wizard',step:4,field:'name',input:'text',value:['Layla’s home bakery','مخبز ليلى المنزلي'],target:'w5'},
    {id:'w5',feature:1,title:['Are you starting with partners?','هل تبدأ مع شركاء؟'],sub:['Tell us who will own the business.','أخبرنا من سيمتلك المشروع.'],kind:'wizard',step:5,field:'partners',options:[['Just me','أنا فقط'],['With partners','مع شركاء']],target:'w6'},
    {id:'w6',feature:1,title:['What is your starting capital?','ما رأس المال الأولي؟'],sub:['Enter an estimate in Jordanian dinars.','أدخل تقديراً بالدينار الأردني.'],kind:'wizard',step:6,field:'capital',input:'number',value:['2500','2500'],target:'w7'},
    {id:'w7',feature:13,title:['Will anyone work with you?','هل سيعمل أحد معك؟'],sub:['We will flag requirements to verify before launch.','سنوضح المتطلبات التي يجب التحقق منها قبل الإطلاق.'],kind:'wizard',step:7,field:'staff',options:[['No employees yet','لا يوجد موظفون حالياً'],['One employee','موظف واحد'],['Two or more','اثنان أو أكثر']],target:'w8'},
    {id:'w8',feature:1,title:['What support do you need?','ما الدعم الذي تحتاجه؟'],sub:['Choose your first priority.','اختر أولويتك الأولى.'],kind:'wizard',step:8,field:'support',options:[['Business account','حساب تجاري'],['Incubator support','دعم حاضنة'],['Funding','تمويل']],target:'wizard-review'},
    {id:'wizard-review',feature:1,title:['Ready for your next chapter?','هل أنت جاهز للخطوة التالية؟'],sub:['Review your answers before creating your roadmap.','راجع إجاباتك قبل إنشاء مسار مشروعك.'],kind:'review',action:['Create my roadmap','إنشاء مسار مشروعي'],target:'roadmap',rows:[['Business','Home bakery','مخبز منزلي'],['City','Irbid','إربد'],['Premises','From home','من المنزل'],['Capital','2,500 JOD','٢٬٥٠٠ دينار'],['Ownership','Sole owner','مالك واحد']]},
    {id:'roadmap',feature:[2,10,13],title:['A clear path to opening day','مسار واضح ليوم الافتتاح'],sub:['Welcome, Layla. Start with your documents; we’ll keep the next step in sight.','مرحباً ليلى. ابدئي بالمستندات وسنوضح لك الخطوة التالية.'],kind:'roadmap',action:['Prepare documents','تجهيز المستندات'],target:'documents',rows:[['01','Confirm identity','تأكيد الهوية','Completed','مكتمل'],['02','Prepare documents','تجهيز المستندات','Needs action','يتطلب إجراء'],['03','Register business','تسجيل المشروع','Locked','مقفل'],['04','Municipal review','مراجعة البلدية','Locked','مقفل'],['05','Tax & social security','الضرائب والضمان','Locked','مقفل'],['06','Open business account','فتح حساب تجاري','Locked','مقفل']],note:['Home-based track · fee estimate 120 JOD · 7–14 days. All figures are sample data, not official fees.','المسار المنزلي · تكلفة توضيحية ١٢٠ ديناراً · ٧–١٤ يوماً. جميع الأرقام نموذجية وليست رسوماً رسمية.']},
    {id:'documents',feature:[3,9],title:['Your documents, together','مستنداتك في مكان واحد'],sub:['Upload once. Review extracted details before they are reused.','ارفع مرة واحدة وراجع البيانات المستخرجة قبل إعادة استخدامها.'],kind:'documents',action:['Review extracted details','مراجعة البيانات المستخرجة'],target:'ocr',rows:[['ID','National identity','الهوية الوطنية','Verified sample','نموذج موثق'],['HOME','Home-use consent','موافقة الاستخدام المنزلي','Missing document','مستند ناقص'],['ADDR','Address evidence','إثبات العنوان','Blurry sample · replace','نموذج غير واضح · استبداله']]},
    {id:'ocr',feature:3,title:['Check the extracted details','تحقق من البيانات المستخرجة'],sub:['You stay in control of what goes into your forms.','أنت تتحكم بالبيانات المستخدمة في نماذجك.'],kind:'ocr',action:['Confirm details','تأكيد البيانات'],target:'signing',rows:[['Full name','Layla Ahmad','ليلى أحمد'],['Business name','Layla’s home bakery','مخبز ليلى المنزلي'],['City','Irbid','إربد']],note:['Sample OCR preview · edit incorrect fields before confirming.','معاينة استخراج تجريبية · عدّل الحقول غير الصحيحة قبل التأكيد.']},
    {id:'signing',feature:4,title:['Review. Sign. Move forward.','راجع ووقّع وتقدم.'],sub:['Review each generated document before your demo signature.','راجع كل مستند مولّد قبل التوقيع التجريبي.'],kind:'signing',action:['Sign all documents','توقيع جميع المستندات'],target:'signed',rows:[['01','Registration application','طلب التسجيل','Ready for review','جاهز للمراجعة'],['02','Home-use declaration','إقرار الاستخدام المنزلي','Ready for review','جاهز للمراجعة'],['03','Partner consent','موافقة مشاركة البيانات','Ready for review','جاهز للمراجعة']],note:['Demo signature only · no legally binding signature is created.','توقيع تجريبي فقط · لا يتم إنشاء توقيع ملزم قانونياً.']},
    {id:'signed',feature:4,title:['Your documents are signed','تم توقيع مستنداتك'],sub:['Three demo documents are ready for your partner applications.','ثلاثة مستندات تجريبية جاهزة لطلبات الشركاء.'],kind:'success',action:['Explore incubators','استكشاف الحاضنات'],target:'incubators',rows:[['03','Documents signed','مستندات موقعة'],['Today','Demo audit trail saved','تم حفظ سجل التوقيع التجريبي']]},
    {id:'incubators',feature:5,title:['Find the right support','اعثر على الدعم المناسب'],sub:['Matches explain why each programme fits your business. All partners below are fictional.','توضح الترشيحات سبب ملاءمة كل برنامج. الجهات التالية افتراضية.'],kind:'matches',action:['Apply to selected','التقديم للجهات المحددة'],target:'applied',rows:[['94%','North Growth Lab','مختبر نمو الشمال','Irbid · food businesses · idea stage','إربد · مشاريع غذائية · مرحلة الفكرة'],['87%','Women Build Hub','مركز رائدات الأعمال','Home businesses · mentoring · early stage','مشاريع منزلية · إرشاد · مرحلة مبكرة'],['79%','Launch Collective','ملتقى الانطلاق','National programme · market access','برنامج وطني · الوصول للأسواق']]},
    {id:'applied',feature:5,title:['Your next connections are on their way','طلباتك جاهزة للمراجعة'],sub:['Selected applications are submitted in this demo. You can follow their status here.','تم إرسال الطلبات المحددة تجريبياً ويمكنك متابعة حالتها هنا.'],kind:'success',action:['Prepare bank file','تجهيز الملف البنكي'],target:'bank',rows:[['01','Application received','تم استلام الطلب'],['02','Partner review','مراجعة الشريك']]},
    {id:'bank',feature:6,title:['A complete file for your bank','ملف متكامل لبنكك'],sub:['Review your profile, signed documents, and business plan in one package.','راجع ملفك ومستنداتك الموقعة وخطة العمل في حزمة واحدة.'],kind:'bank',action:['Review and send','المراجعة والإرسال'],target:'bank-sent',rows:[['01','Business profile','ملف المشروع','Complete','مكتمل'],['02','Signed documents','المستندات الموقعة','3 documents','٣ مستندات'],['03','Business plan','خطة العمل','Draft ready','المسودة جاهزة']],options:[['Demo SME Bank','بنك المشاريع التجريبي'],['Demo Community Bank','بنك المجتمع التجريبي']]},
    {id:'bank-sent',feature:6,title:['Bank file submitted','تم إرسال الملف البنكي'],sub:['Your sample bank has received the demo package.','استقبل البنك النموذجي الحزمة التجريبية.'],kind:'success',action:['Book a visit','حجز زيارة'],target:'appointments',rows:[['BD-1042','Submission reference','مرجع الإرسال'],['Review','Awaiting partner response','بانتظار رد الشريك']]},
    {id:'assistant',feature:8,title:['A little clarity, whenever you need it','إجابة واضحة عندما تحتاجها'],sub:['Ask about your documents, roadmap, or next step.','اسأل عن مستنداتك أو مسار مشروعك أو الخطوة التالية.'],kind:'chat',rows:[['You','What should I prepare for the home-business review?','ماذا أجهز لمراجعة المشروع المنزلي؟'],['Bedaya','In this demo, prepare your identity, address evidence, and home-use consent. Confirm the exact requirements with your municipality before applying.','في هذا العرض، جهز الهوية وإثبات العنوان وموافقة الاستخدام المنزلي. تحقق من المتطلبات الدقيقة لدى البلدية قبل التقديم.']]},
    {id:'notifications',feature:11,title:['Stay one step ahead','ابق على اطلاع'],sub:['Updates that matter to your launch.','تحديثات مهمة لإطلاق مشروعك.'],kind:'notifications',action:['Mark all as read','تحديد الكل كمقروء'],rows:[['Today','Your bank file was received','تم استلام ملفك البنكي','Application BD-1042','الطلب BD-1042'],['Today','A clearer address document is needed','نحتاج مستند عنوان أوضح','Open your document vault','افتح خزنة المستندات'],['Tomorrow','Your visit is coming up','موعد زيارتك يقترب','Review your appointment','راجع موعدك']]},
    {id:'appointments',feature:12,title:['Make room for your next step','حدد موعداً لخطوتك التالية'],sub:['Choose a partner and a time that works for you.','اختر الجهة والوقت المناسب لك.'],kind:'calendar',action:['Book appointment','حجز موعد'],rows:[['12','Monday · 12 October','الاثنين · ١٢ أكتوبر','09:00 · 11:30 · 14:00','09:00 · 11:30 · 14:00'],['13','Tuesday · 13 October','الثلاثاء · ١٣ أكتوبر','10:00 · 13:00','10:00 · 13:00']],options:[['Demo SME Bank','بنك المشاريع التجريبي'],['North Growth Lab','مختبر نمو الشمال'],['Municipality demo desk','مكتب البلدية التجريبي']]},
    {id:'plan',feature:14,title:['Your idea, on paper','فكرتك على الورق'],sub:['A concise plan built from your answers. Review it before sharing.','خطة مختصرة من إجاباتك. راجعها قبل المشاركة.'],kind:'plan',action:['Download plan','تنزيل الخطة'],rows:[['01','Business summary','ملخص المشروع','A home bakery in Irbid offering made-to-order pastries.','مخبز منزلي في إربد يقدم معجنات حسب الطلب.'],['02','Customers & channels','العملاء والقنوات','Local families; direct orders and social media.','العائلات المحلية؛ الطلب المباشر ووسائل التواصل.'],['03','Starting resources','الموارد الأولية','Sample capital: 2,500 JOD. Owner-operated at home.','رأس مال نموذجي: ٢٬٥٠٠ دينار. تديره المالكة من المنزل.']]},
    {id:'compliance',feature:17,title:['Keep your business on track','حافظ على انتظام مشروعك'],sub:['A calendar for obligations after launch. Dates below are illustrative.','تقويم للالتزامات بعد الإطلاق. التواريخ التالية توضيحية.'],kind:'compliance',rows:[['15 NOV','Tax review','مراجعة الضرائب','Confirm applicability and dates','تحقق من الانطباق والمواعيد'],['01 DEC','Social security review','مراجعة الضمان الاجتماعي','Confirm if employees are registered','تحقق من تسجيل الموظفين'],['01 OCT','License renewal reminder','تذكير تجديد الترخيص','Review with issuing authority','راجع الجهة المصدرة']]},
    {id:'location',feature:18,title:['Check before you commit','تحقق قبل أن تلتزم'],sub:['Preview an address check before choosing premises.','عاين فحص العنوان قبل اختيار موقع المشروع.'],kind:'location',action:['Check address','فحص العنوان'],rows:[['HOME','Irbid · sample residential zone','إربد · منطقة سكنية نموذجية','Conditional match · municipality review required','توافق مشروط · تتطلب مراجعة البلدية']],note:['Illustrative zoning result; not an official approval.','نتيجة تنظيمية توضيحية؛ ليست موافقة رسمية.']},
    {id:'funding',feature:19,title:['Funding that fits your stage','تمويل يناسب مرحلتك'],sub:['Compare fictional offers for your demo business profile.','قارن عروضاً افتراضية لملف مشروعك التجريبي.'],kind:'funding',rows:[['GRANT','Demo Launch Grant','منحة الانطلاق التجريبية','Up to 3,000 JOD · early-stage businesses','حتى ٣٬٠٠٠ دينار · مشاريع مبكرة'],['LOAN','Demo Microfinance','التمويل الأصغر التجريبي','1,000–5,000 JOD · terms require review','١٬٠٠٠–٥٬٠٠٠ دينار · مراجعة الشروط'],['SUPPORT','Demo Equipment Support','دعم المعدات التجريبي','Equipment contribution · food businesses','مساهمة في المعدات · مشاريع غذائية']]},
    {id:'experts',feature:20,title:['Get help with the hard part','احصل على مساعدة عند الحاجة'],sub:['Fictional expert profiles for the hackathon prototype.','ملفات خبراء افتراضية لنموذج الهاكاثون.'],kind:'experts',rows:[['SA','Sara Ali','سارة علي','Accountant · tax registration · 25 JOD sample session','محاسبة · التسجيل الضريبي · جلسة نموذجية ٢٥ ديناراً'],['OK','Omar Khalil','عمر خليل','Legal advisor · registration · 35 JOD sample session','مستشار قانوني · التسجيل · جلسة نموذجية ٣٥ ديناراً']]},
    {id:'invoicing',feature:21,title:['Prepare for e-invoicing','استعد للفوترة الإلكترونية'],sub:['Review business details before connecting to a real service.','راجع بيانات المشروع قبل الربط بخدمة فعلية.'],kind:'invoicing',action:['Save readiness checklist','حفظ قائمة الجاهزية'],rows:[['01','Business details','بيانات المشروع','Ready','جاهزة'],['02','Tax number','الرقم الضريبي','Needs confirmation','يحتاج إلى تأكيد'],['03','Invoice template','نموذج الفاتورة','Draft','مسودة'],['04','Service connection','ربط الخدمة','Not connected in demo','غير متصل في العرض']]},
    {id:'partner',feature:15,title:['A better start for every application','بداية أفضل لكل طلب'],sub:['Review complete profiles and keep owners informed.','راجع الملفات وأبق أصحاب المشاريع على اطلاع.'],kind:'partner',action:['Review application','مراجعة الطلب'],target:'application',rows:[['BD-1042','Layla’s home bakery','مخبز ليلى المنزلي','New · Irbid · home business','جديد · إربد · مشروع منزلي'],['BD-1039','Demo online store','متجر إلكتروني تجريبي','In review · Amman','قيد المراجعة · عمّان'],['BD-1036','Demo service company','شركة خدمات تجريبية','Approved · Zarqa','مقبول · الزرقاء']]},
    {id:'application',feature:15,title:['Layla’s home bakery','مخبز ليلى المنزلي'],sub:['Application BD-1042 · received today · sample profile','الطلب BD-1042 · وصل اليوم · ملف نموذجي'],kind:'application',rows:[['PROFILE','Owner profile','ملف المالكة','Demo verified identity','هوية موثقة تجريبياً'],['DOCS','Documents','المستندات','Address evidence needs replacement','يحتاج إثبات العنوان إلى استبدال'],['PLAN','Business plan','خطة العمل','Ready for review','جاهزة للمراجعة']]},
    {id:'admin',feature:16,title:['Manage the launch framework','إدارة إطار إطلاق المشاريع'],sub:['Maintain the demo steps, rules, fees, partners, and user access.','إدارة الخطوات والقواعد والرسوم والشركاء وصلاحيات المستخدمين التجريبية.'],kind:'admin',action:['Save changes','حفظ التغييرات'],rows:[['RULE','Home bakery · Irbid','مخبز منزلي · إربد','6 steps · draft rules','٦ خطوات · قواعد مسودة'],['FEE','Municipal review fee','رسوم مراجعة البلدية','Sample 50 JOD · unverified','٥٠ ديناراً نموذجياً · غير موثقة'],['PARTNER','North Growth Lab','مختبر نمو الشمال','Active demo partner','شريك تجريبي نشط'],['USER','Layla Ahmad','ليلى أحمد','Owner · demo access','مالكة · وصول تجريبي']]},
    {id:'analytics',feature:22,title:['See where progress slows','اعرف أين يتباطأ التقدم'],sub:['Anonymous, synthetic data helps identify friction in the journey.','بيانات اصطناعية مجهولة توضح نقاط التعثر في الرحلة.'],kind:'analytics',rows:[['4.8','Municipal review','مراجعة البلدية','Average days · 22% sample drop-off','متوسط الأيام · تسرب نموذجي ٢٢٪'],['2.6','Document preparation','تجهيز المستندات','Average days · 14% sample drop-off','متوسط الأيام · تسرب نموذجي ١٤٪'],['1.4','Bank review','مراجعة البنك','Average days · 8% sample drop-off','متوسط الأيام · تسرب نموذجي ٨٪'],['0.8','Business registration','تسجيل المشروع','Average days · 5% sample drop-off','متوسط الأيام · تسرب نموذجي ٥٪']]}
  ]
};
