import { readFile, writeFile, mkdir } from 'node:fs/promises';
const k=JSON.parse(await readFile('lib/integrations/knowledge.json','utf8'));
const partners=JSON.parse(await readFile('data/m1/incubators.json','utf8'));
const payload={version:k.version,disclaimer:k.disclaimer,provenance:{repo:'https://github.com/Amin-Shahin-00/Beluga_HTU',branch:'M5_Ameen',commit:'00a3d0207222073c7812e2360afbd96f0337c1b7',verification:'team-supplied; not independently re-verified'},steps:Object.entries(k.legalForms).flatMap(([form,info])=>info.steps.map(step=>({...step,key:step.id,legalForm:form}))),sources:k.sources,offices:k.offices,documents:k.documents};
const entries=[['rules-team-v1','rules',payload,false],...partners.map(partner=>[partner.id,'partner',{...partner,kind:'incubator',submissionMode:'internal_demo',formFieldsVerified:false},false]),['bank-demo','partner',{id:'bank-demo',kind:'bank',name:{ar:'بنك تجريبي — ليس جهة حقيقية',en:'Demo Bank — fictional'},requirements:['business_profile','business_plan','signed_documents'],submissionMode:'internal_demo'},true],['compliance-demo','compliance',{items:[{key:'license-review',title_ar:'مراجعة تجديد الترخيص (موعد تجريبي)',title_en:'License review (demo deadline)',months:12,office:'Demo municipality'},{key:'tax-review',title_ar:'مراجعة الضرائب (موعد تجريبي)',title_en:'Tax review (demo deadline)',months:3,office:'Demo tax office'},{key:'social-review',title_ar:'مراجعة الضمان (موعد تجريبي)',title_en:'Social security review (demo deadline)',months:1,office:'Demo SSC'}]},true],['location-demo','location',{areas:[{name:'Demo Amman Area A',activities:['retail','services']},{name:'Demo Amman Area B',activities:['food','tech']}],disclaimer:'Fictional zoning only; not a check of a real address.'},true]];
for(let index=0;index<6;index++) {const date=new Date();date.setUTCDate(date.getUTCDate()+index+1);date.setUTCHours(7+index%3,0,0,0);entries.push([`slot-demo-${index+1}`,'slot',{partner_key:index%2?'bank-demo':'jedco_hbb',starts_at:date.toISOString(),duration_minutes:30,timezone:'Asia/Amman',is_demo:true},true]);}
const literal=v=>"'"+JSON.stringify(v).replaceAll("'","''")+"'::jsonb";
const sql='begin;\n'+entries.map(([key,kind,data,demo])=>`insert into public.bedaya_catalog(key,kind,payload,is_demo) values('${key}','${kind}',${literal(data)},${demo}) on conflict(key) do nothing;`).join('\n')+'\ncommit;\n';
await mkdir('supabase/seeds',{recursive:true});await writeFile('supabase/seeds/team.sql',sql);console.log('Generated team catalog with source metadata and clearly separate demo banks, appointments, zoning and deadlines.');
