import assert from 'node:assert/strict';
import { profileSchema, draftSchema, summarize, teamEstimate } from '../lib/platform/team';
import { rankIncubators } from '../lib/platform/ranking';
import { complianceDates } from '../lib/platform/domain';
import { fileSignature, safeFilename, autofillPdf } from '../lib/platform/files';
import { PDFDocument } from 'pdf-lib';
import fixture from '../lib/integrations/fixtures/user-profile.layla.json';
const {userId,...input}=fixture;
const profile={...profileSchema.parse(input),userId};
assert.equal(profileSchema.safeParse({...input,userId:'forged'}).success,false,'Client identity must be rejected');
assert.equal(profileSchema.safeParse({...input,personal:{...input.personal,birthDate:'2026-99-99'}}).success,false,'Invalid date');
assert.equal(profileSchema.safeParse({...input,business:{...input.business,homeBased:false}}).success,false,'Inconsistent legal form');
assert(draftSchema.safeParse({business:{sector:'food'}}).success,'Partial draft is valid');
const costs=teamEstimate(profile);
assert(costs.steps.some(step=>step.id==='jfda_home_food_license'),'Food path must include JFDA');
assert(costs.range.unknownSteps.includes('gam_rental_certificate'),'Variable rent fee must stay unknown');
assert.equal(costs.range.maxJod,null,'Unknown fee must not be disguised as zero');
const owned={...profile,business:{...profile.business,premises:'owned' as const,wantsTradeName:false,employeesPlanned:0}};
const other=teamEstimate(owned);
assert(!other.steps.some(step=>step.id==='gam_rental_certificate'),'Owned premises have no rent step');
assert(!other.steps.some(step=>step.id==='reserve_trade_name'),'Optional name step is conditional');
assert(other.steps.some(step=>step.id==='social_security'),'Preserve the supplied always-required SSC step; do not silently change M1 data');
const llc={...profile,business:{...profile.business,homeBased:false,legalForm:'llc' as const}};
assert(teamEstimate(llc).steps.some(step=>step.id==='register_llc'),'LLC registration path');
const tasks=costs.steps.slice(0,2).map((step,index)=>({id:String(index),step_key:step.id,title_ar:step.title.ar,title_en:step.title.en,office:step.officeId,documents:[],dependencies:index?[costs.steps[0].id]:[],status:'pending',fee_min:step.fee.minJod,fee_max:step.fee.maxJod,days:step.days.value,details:{},is_demo:false}));
assert(summarize(tasks).steps[1].locked,'Dependencies lock later steps');
tasks[0].status='done';assert(!summarize(tasks).steps[1].locked);assert.equal(summarize(tasks).progress,50);
const ranks=rankIncubators(profile,'2026-10-09');assert(ranks.some(row=>row.incubatorId==='jedco_hbb'),'Home food matches expected sourced programme');
assert(ranks.every(row=>row.score<=1&&row.score>=0),'M5 ranking score contract');
assert.equal(complianceDates('2027-01-31',[{key:'test',title_ar:'test',title_en:'test',months:1,office:'demo'}])[0].dueDate,'2027-02-28','Month-end clamps to a real date');
assert(fileSignature(new TextEncoder().encode('%PDF-1.7'),'application/pdf'));
assert(!fileSignature(new TextEncoder().encode('not a pdf'),'application/pdf'));
assert(!safeFilename('../../private.pdf').includes('/'),'Archive filenames cannot traverse paths');
const bytes=await autofillPdf(profile);const pdf=await PDFDocument.load(bytes);assert(pdf.getPageCount()>=1,'Arabic autofill PDF is readable');
console.log('PASS: platform validation, four-case rules, conditional steps, ranges, dependencies, ranking, date arithmetic, file validation and Arabic PDF');
