-- Run in Supabase SQL Editor. Transactional, preserves existing business rows.
begin;
create table if not exists public.businesses (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null,
  city text not null,
  status text not null default 'New',
  created_at timestamptz not null default now(),
  user_id uuid not null references auth.users(id)
);
alter table public.businesses add column if not exists user_id uuid;
-- Stop safely if the existing id column has no generator; do not rewrite IDs.
do $$ begin
  if not exists (select 1 from information_schema.columns where table_schema = 'public' and table_name = 'businesses' and column_name = 'id' and (is_identity = 'YES' or column_default is not null)) then
    raise exception 'businesses.id needs an identity/default generator. No changes committed.';
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.businesses'::regclass and conname = 'bedaya_owner_required') then
    alter table public.businesses add constraint bedaya_owner_required check (user_id is not null) not valid;
  end if;
  if not exists (select 1 from pg_constraint where conrelid = 'public.businesses'::regclass and conname = 'bedaya_owner_fk') then
    alter table public.businesses add constraint bedaya_owner_fk foreign key (user_id) references auth.users(id) not valid;
  end if;
end $$;
create index if not exists businesses_owner_created_idx on public.businesses(user_id, created_at desc);
alter table public.businesses enable row level security;
revoke all on public.businesses from anon;
grant select, insert, update, delete on public.businesses to authenticated;
-- Restrictive guard also limits any pre-existing permissive policies.
drop policy if exists bedaya_owner_guard on public.businesses;
create policy bedaya_owner_guard on public.businesses as restrictive for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
drop policy if exists bedaya_owner_access on public.businesses;
create policy bedaya_owner_access on public.businesses for all to authenticated
  using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
do $$ declare seq text; begin
  seq := pg_get_serial_sequence('public.businesses', 'id');
  if seq is not null then
    execute format('grant usage, select on sequence %s to authenticated', seq);
  end if;
end $$;
commit;
-- Existing unowned rows remain hidden. Assign owners deliberately before validating
-- bedaya_owner_required and bedaya_owner_fk; never guess ownership or delete rows.
